services:
    cos_rest_client.endpoint_loader:
        class: Cos\RestClientBundle\Endpoint\EndpointLoader
        arguments: ["@annotation_reader", "@cos_rest_client.endpoint_collection", "@cos_rest_client.endpoint_factory", "%cos_rest_client.clients%"]
        public: false

    cos_rest_client.endpoint_collection:
        class: Cos\RestClientBundle\Endpoint\EndpointCollection
        public: false

    cos_rest_client.endpoint_factory:
        class: Cos\RestClientBundle\Endpoint\EndpointFactory
        public: false

    cos_rest_client.request_builder:
        class: Cos\RestClientBundle\Request\RequestBuilder
        public: false

    cos_rest_client.request_executor:
        class: Cos\RestClientBundle\Request\RequestExecutor
        arguments: ["@cos_rest_client.guzzle.client"]
        public: false

    cos_rest_client.guzzle.client:
        class: GuzzleHttp\Client
        public: false

    cos_rest_client.rest_adapter:
        class: Cos\RestClientBundle\Adapter\RestAdapter
        arguments: ["@cos_rest_client.request_executor", "@cos_rest_client.endpoint_collection", "@cos_rest_client.request_builder"]
        public: false

    cos_rest_client.proxy_factory:
        class: Cos\RestClientBundle\Factory\RestProxyFactory
        arguments: ["@cos_rest_client.rest_adapter", "@cos_rest_client.endpoint_loader", "@cos_rest_client.request_builder"]

